package lastfm

import (
	"encoding/xml"
	"net/http"
)

type xmlBase struct {
	XMLName xml.Name `xml:"lfm"`
	Status  string   `xml:"status,attr"`
	Inner   []byte   `xml:",innerxml"`
}

// Auth contains the response for the LastFM Login endpoint.
type Auth struct {
	Name       string `xml:"name"`
	Key        string `xml:"key"`
	Subscriber bool   `xml:"subscriber"`
}

// Error contains the error response generated by the LastFM API.
type Error struct {
	ErrorCode int    `json:"error"`
	Message   string `json:"message"`
}

// Client is the LastFM client.
type Client struct {
	APIKey     string
	APISecret  string
	httpClient *http.Client
	limit      int
	sessionKey string
	useragent  string
}

// Provider contains details about a LastFM API request.
//
// This structure is usually used by functions abstracting the LastFM API.
type Provider struct {
	Method   string
	Params   map[string]string
	Response interface{}
	Type     string
}

// Scrobble contains the track scrobble data to be sent to LastFM.
type Scrobble struct {
	Artist       string
	Track        string
	Timestamp    int64
	Album        string
	Context      string
	StreamID     string
	ChosenByUser bool
	TrackNumber  int
	MBID         string
	AlbumArtist  string
	Duration     int64
}
